# Login page

LOG_IN_BTN_XPATH = '//*[@id="ShopifyMainNav"]/ul[2]/li[2]'
FILL_EMAIL_XPATH = '//*[@id="account_email"]'
BTN_NEXT_XPATH = '//*[@id="body-content"]/div[1]/div[2]/div/form/button'
FILL_PASS_XPATH = '//*[@id="account_password"]'
BTN_LOGIN_XPATH = '//*[@id="login_form"]/button'
STORE_PAGE_XPATH = '//*[@id="AppFrameAside"]/div[1]/div[2]/div/div/nav/ul[1]/li[1]/a/span'
BTN_ADD_STORE_XPATH = '//*[@id="AppFrameMain"]/div/div/div/div/div/section/div[1]/div[2]/ul/li'
BTN_SELECT_DEV_STORE_XPATH = '//*[@id="PolarisChoiceList1"]/ul/li[1]/div/label/span[1]/span/span[1]'
FILL_STORE_NAME_XPATH = '//*[@id="PolarisTextField1"]'
FILL_PASS_STORE_XPATH = '//*[@id="PolarisTextField4"]'
FILL_CONFIRM_PASS_STORE_XPATH = '//*[@id="PolarisTextField5"]'
FILL_ADDRESS_XPATH = '//*[@id="PolarisTextField6"]'
FILL_CITY_XPATH = '//*[@id="PolarisTextField7"]'
FILL_ZIPCODE_XPATH = '//*[@id="PolarisTextField8"]'
BTN_SELECT_TEST_APP_XPATH = '//*[@id="signup_source_details"]/ul/li[2]/label/span[2]'
BTN_SAVE_XPATH = '//*[@id="AppFrameMain"]/div/div/div[2]/div[2]/div/div[2]/button'
BTN_ADD_STORE_AGAIN_XPATH = '//*[@id="AppFrameMain"]/header/div[1]/div[2]/div'
BTN_SELECT_APP_XPATH = '//*[@id="AppFrameNav"]/nav/div[2]/ul[1]/li[8]/div' 
BTN_SELECT_VISIT_APP_XPATH = '//*[@id="AppFrameMain"]/div/div/div[1]/div/div[2]'
FILL_VALUE_SEARCH_XPATH = '//*[@id="ui-app-store-hero__home-search"]/label'
BTN_SEARCH_XPATH = '//*[@id="ui-app-store-hero__home-search"]/button'
SALES_APP_XPATH = '//*[@title="Go to Sales Box ‑ Shipping & Offers"]'
BTN_ADD_APP_XPATH = '//*[@id="Main"]/section[1]/div/div/div/div[6]/form/input[2]'
BTN_INSTALL_XPATH = '//*[@id="proceed_cta"]'
BTN_SELECT_CHARGE_XPATH = '//*[@id="pricing-sales-box"]/div/div[2]/div[2]/div/div/div[2]/button'
BTN_CHARGE_XPATH = '//*[@id="charges_form"]'
SELECT_STORE_XPATH = '//*[@id="AppFrameMain"]/div/div[1]/div[1]/div[2]/ul/li[1]'
BTN_LOGIN_STORE_XPATH = '//*[@id="AppFrameMain"]/header/div[1]/div[2]/div'

